name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    name: Lint
    uses: the-guild-org/shared-config/.github/workflows/lint.yml@main
    with:
      script: pnpm ci:lint
      packageManager: pnpm
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}

  typecheck:
    name: typecheck / graphql v${{matrix.graphql_version}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        graphql_version: [15, 16]

    steps:
      - name: Checkout Master
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup ENV
        uses: the-guild-org/shared-config/setup@main
        with:
          nodeVersion: 18
          packageManager: pnpm

      - name: Build
        run: pnpm build

  test:
    name: Node.js v${{matrix.node_version}} / GraphQL v${{matrix.graphql_version}} / ESLint v8
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs: [typecheck]
    strategy:
      matrix:
        node_version: [18, 20.7]
        graphql_version: [16]

    steps:
      - name: Checkout Master
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup ENV
        uses: the-guild-org/shared-config/setup@main
        with:
          nodeVersion: ${{matrix.node_version}}
          packageManager: pnpm

      - name: Test
        run: pnpm test

      - name: Type Check
        run: pnpm typecheck
#
#      - name: Lint Prettier
#        run: pnpm lint:prettier
